# Generated by Django 5.2.1 on 2025-05-18 07:48

import django.db.models.deletion
from django.db import migrations, models

def add_gradetype_data(apps, schema_editor):
    GradeType = apps.get_model('grade', 'GradeType')
    
    GradeType.objects.create(name="activity")
    GradeType.objects.create(name="quiz")
    GradeType.objects.create(name="examination")
    
def create_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser('admin', 'admin@example.com', 'password')
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_enrollment_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.enrollment')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade.gradetype')),
            ],
        ),
        migrations.RunPython(add_gradetype_data),
        migrations.RunPython(create_admin_user),
    ]
