# Generated by Django 5.2.1 on 2025-05-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_grade_max_score_grade_name_grade_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
