# Generated by Django 5.2.1 on 2025-05-31 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0003_alter_grade_max_score_alter_grade_score'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.subject'),
            preserve_default=False,
        ),
    ]
